services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: onlinejudge
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"

  api:
    build:
      context: .          # chính là thư mục OnlineJudgeAPI
      dockerfile: Dockerfile  
    container_name: onlinejudge-api
    ports:
      - "5024:5024"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql-db;port=3306;database=onlinejudge;user=root;password=123123
      - Redis__Connection=redis-cache:6379
    depends_on:
      - mysql
      - redis

  frontend:
    build:
      context: ./wwwroot
      dockerfile: ../Dockerfile.frontend
    container_name: onlinejudge-frontend
    ports:
      - "3000:80"

volumes:
  mysql_data:
